### ISSUE TITLE
반응형 웹사이트

### ISSUE THREAD

**Issue by cjfghk5697** [wkazxf/Ajou-Univ-coronic-travel-path-#1]
안녕하세요 프론트엔드는 잘 모르지만 이런 점이 개선/추가되면 좋을 거 같아 한번 이슈를 남겨봅니다!

- 모바일 반응
![image](https://user-images.githubusercontent.com/80466735/131618010-c0888ed0-e024-4426-bf34-6a498ecd02d9.png)
모바일 같은 경우 화면이 깨지는 거 같아서 left, right Margin, height 등을 %로 추가하거나 수정하여 반응형으로 만들어보는 건 어떠신가요?
- 버튼 디자인
부트스트랩을 이용해서 버튼 디자인을 좀 더 예쁘게 하면 더욱더 좋을 거 같습니다!
ex)
``` html
  <button class="btn btn-primary" id="inbutton1" onclick="location.href='/templates/Enrollment.html'">회원가입</button>
```

제가 아직 많이 부족해서 개선책이 틀렸을 수도 있지만 반응형이나 디자인이 좀 아쉽다고 생각해서 이슈 남겨보겠습니다

**Comment by hwanld** [comment]
솔직하게 말씀드리면 제가 백엔드 개발자중에서 클라우드 서버 개발자를 목표로 하고 있고, 프론트엔드는 제가 만든 프로젝트들을 구현하는 정도로만 배워서 프론트엔드를 할 줄 아는 백엔드 개발자가 되어보자! 라는 생각으로 시작하여서 아직 저도 지식이 한참 부족합니다 ㅠㅠ
 말씀하신 것 처럼 모바일의 경우는 화면이 깨지는데 제 html이랑 css 코드 보시면 제가 media quary를 사용해서 min-width를 980px로 설정하고 inner class로 정의한 다음에 모든 요소들을 inner 태그 안에다가 넣었습니다. (일반적인 모바일의 가로 픽셀이 980px이라고 하더라구요 그래서 모바일에서도 크롬 브라우저 등에서 '데스크탑으로 보기'를 사용하면 딱 맞게 나오구요) 모바일 화면이 깨지는 부분을 아까 다른 분께서 PR 보내주신다 하셔서 보고 참조해서 공부해 보려고 합니다!
 말씀하신 버튼은 제가 어제 처음 게시물을 올렸을 때 어떤 분께서 '버튼이 있었으면 좋겠다!' 라고 말씀을 하셔서 20분 정도만에 급하게 만든 버튼이라 아직은 좀 디자인이 구립(?)니다ㅋㅋㅋ 말씀하신 코드 참고해서 오늘 중으로 수정 한번 해 보겠습니다!
 좋은 말씀 너무 감사하고, 많은 관심 가져주신 만큼 더욱 열심히 노력하겠습니다! 먼 훗날 꼭 서로 좋은 개발자로 자리하길 기원하겠습니다. 진심으로 감사합니다!

**Comment by cjfghk5697** [comment]
아아 넵ㅎㅎ
 좋은 결과 나오시길 바랍니다. 이슈 닫겠습니다!
